version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR started on `date`
      - aws --version
      - echo Logging into Amazon ECR....
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 844522605599.dkr.ecr.ap-southeast-1.amazonaws.com
      - echo setting repository URI...
      - REPOSITORY_URI=844522605599.dkr.ecr.ap-southeast-1.amazonaws.com/fencing-cs203-repo
      - echo setting image tag...
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - cd backend  # Change to the backend directory
  build:
    commands:
      - echo building and tagging started image on `date`
      - echo running mvn clean install...
      - mvn clean install -e
      - echo building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - echo tagging the Docker image...
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo pushing Docker image to Amazon ECR started on `date`
      - echo pushing to repository...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo setting container name...
      - DOCKER_CONTAINER_NAME=cs203-fencing-cs203-container
      - echo writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > backend/imagedefinitions.json
      - echo printing imagedefinitions file
      - cat backend/imagedefinitions.json
artifacts:
  files: backend/imagedefinitions.json
  
